// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZcVAYf_Q77reN3oo2-JBnNoDgRlK7fGQ',
    appId: '1:196362470450:android:73cb5121f1bc4077f4e82b',
    messagingSenderId: '196362470450',
    projectId: 'renew-yakio',
    storageBucket: 'renew-yakio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhDiR72RJ0lcPHMeEoA-Id8s7CJ3ZASVM',
    appId: '1:196362470450:ios:27297f382669ada2f4e82b',
    messagingSenderId: '196362470450',
    projectId: 'renew-yakio',
    storageBucket: 'renew-yakio.firebasestorage.app',
    iosBundleId: 'com.example.yakiyoNew',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB674P2R3vEgPYyO62ecEjVXf87Aq89POE',
    appId: '1:196362470450:web:d2bf4d76bf5ec6f2f4e82b',
    messagingSenderId: '196362470450',
    projectId: 'renew-yakio',
    authDomain: 'renew-yakio.firebaseapp.com',
    storageBucket: 'renew-yakio.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhDiR72RJ0lcPHMeEoA-Id8s7CJ3ZASVM',
    appId: '1:196362470450:ios:27297f382669ada2f4e82b',
    messagingSenderId: '196362470450',
    projectId: 'renew-yakio',
    storageBucket: 'renew-yakio.firebasestorage.app',
    iosBundleId: 'com.example.yakiyoNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB674P2R3vEgPYyO62ecEjVXf87Aq89POE',
    appId: '1:196362470450:web:7ed03aa4779a3f4ff4e82b',
    messagingSenderId: '196362470450',
    projectId: 'renew-yakio',
    authDomain: 'renew-yakio.firebaseapp.com',
    storageBucket: 'renew-yakio.firebasestorage.app',
  );

}